esphome:
  name: bathroom_lights
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "IoT24"
  password: !secret wifi_password
  fast_connect: true

mqtt:
  broker: box.local

logger:
  level: DEBUG

ota:

web_server:
  port: 80    

sensor:
  - platform: wifi_signal
    name: "Bathroom light WiFi Signal Sensor"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Bathroom light Touchpad 1"
    #on_press:
      #then:
        #- light.toggle: bedroom_light
    on_release:
      then:
        - light.toggle: left_light

#switch:
  #- platform: gpio
    #name: "Bedroom light"
    #pin: GPIO12

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True
  - platform: gpio
    pin: GPIO12
    id: left_relay
    
light:
  - platform: binary
    name: "Bathroom Light L"
    id: left_light
    output: left_relay
  
  - platform: monochromatic
    name: "Bathroom light Touchpad LED Left"
    output: blue_led
