
substitutions:
  devicename: bathroom_lights
  upper_devicename: Bathroom light

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:

web_server:
  port: 80   

sensor:
  - platform: wifi_signal
    name: "Bathroom light WiFi Signal Sensor"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Bathroom LED Touchpad"
    on_press:
      then:
        - light.toggle: led_light

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Bathroom Main Touchpad"
    on_press:
      then:
        - light.toggle: main_light

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True
  - platform: gpio
    pin: GPIO12
    id: led_relay
  - platform: gpio
    pin: GPIO05
    id: main_relay
    
light:
  - platform: binary
    name: "Bathroom LED Light"
    id: led_light
    output: led_relay
  
  - platform: binary
    name: "Bathroom Main Light"
    id: main_light
    output: main_relay
  
  - platform: monochromatic
    name: "Bathroom Touchpad LED"
    output: blue_led
