esphome:
  name: bathroom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: IoT24
  password: !secret wifi_password
  fast_connect: true

mqtt:
  broker: box.local

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
#api:

ota:

web_server:
  port: 80    

switch:

  - platform: gpio
    name: "Occupancy LED"
    pin: 2
    inverted: true
    
sensor:
  - platform: wifi_signal
    name: "Bathroom WiFi Signal Sensor"
    updateInterval: 60s

  - platform: adc
    pin: VCC
    name: "Bathroom VCC Voltage"
