esphome:
  name: bedroom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: IoT24
  password: !secret wifi_password
  fast_connect: true

mqtt:
  broker: box.local

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

web_server:
  port: 80    

sensor:
  - platform: wifi_signal
    name: "Bedroom WiFi RSSi"
    update_interval: 60s

  - platform: adc
    pin: VCC
    name: "Bedroom VCC Voltage"
