
substitutions:
  devicename: bedroom_curtain
  upper_devicename: Bedroom Curtatin


esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  #captive_portal:

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API

api:
  services:
    - service: control_stepper
      variables:
        target: int
      then:
        - stepper.set_target:
            id: ${devicename}
            target: !lambda 'return target;'

ota:

# Example configuration entry
stepper:
  - platform: a4988
    id: ${devicename}
    step_pin: GPIO4
    dir_pin: GPIO2
    max_speed: 500 steps/s

    # Optional:
    acceleration: 100
    deceleration: 100
    sleep_pin: 
      number: GPIO22
      inverted: true
