esphome:
  name: bedroom_light
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "IoT24"
  password: !secret wifi_password
  fast_connect: true

mqtt:
  broker: box.local

# Enable logging
logger:

# Enable Home Assistant API
# api:

ota:

web_server:
  port: 80    

sensor:
  - platform: wifi_signal
    name: "Bedroom light WiFi Signal Sensor"
    update_interval: 60s

  - platform: adc
    pin: VCC
    name: "Bedroom light VCC Voltage"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Bedroom light Touchpad"
    #on_press:
      #then:
        #- light.toggle: bedroom_light
    on_release:
      then:
        - light.toggle: bedroom_light

#switch:
  #- platform: gpio
    #name: "Bedroom light"
    #pin: GPIO12

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True
  - platform: gpio
    pin: GPIO12
    id: main_relay
    
light:
  - platform: binary
    name: "Bedroom Light"
    id: bedroom_light
    output: main_relay
  
  - platform: monochromatic
    name: "Bedroom light Touchpad LED"
    output: blue_led
