esphome:
  name: blebeacon
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

mqtt:
  broker: 192.168.1.5

logger:

ota:

web_server:
  port: 80    

  #esp32_ble_tracker:
  #  scan_interval: 300s

esp32_ble_beacon:
#A4:CF:12:05:BC:DE (unknown)
  type: iBeacon
  uuid: '96fad395-85e5-84b3-0d22-4075109e3804'
  major: 1
  minor: 2

sensor:
  - platform: wifi_signal
    name: "BLE Beacon WiFi Signal Sensor"
    update_interval: 60s

    #binary_sensor:
    #  - platform: ble_presence
    #    mac_address: 98:9E:63:53:20:FD
    #    name: "ESP32 BLE Tracker Jakub - iPhone"


