esphome:
  name: co2
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #fast_connect: true

  #mqtt:
  #  broker: !secret broker_ip

logger:
        #  level: DEBUG

api:          

ota:

web_server:
  port: 80    

uart:
  rx_pin: D7
  tx_pin: D6
  baud_rate: 9600

sensor:
  - platform: mhz19
    co2:
      name: "MH-Z19 CO2 Value"
      id: coval
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 15s

i2c:
    sda: D1
    scl: D2

    #font:
    #  - file: 'fonts/Roboto-Regular.ttf'
    #   id: font1
    #  size: 16

    #display:
    #    - platform: ssd1306_i2c
    #      model: "SSD1306 128x64"
    #      address: 0x3C
    #      lambda: |-
    #        it.printf(0, 30, id(font1), "Co2: %.0fppm", id(coval).state);

