esphome:
  name: co2
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

mqtt:
  broker: !secret broker_ip

logger:

api:

ota:

        #web_server:
        #  port: 80    

uart:
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600
  id: uart_co


sensor:
  - platform: mhz19
    uart_id: uart_co
    co2:
      name: "CO2"
      id: coval
    temperature:
      name: "CO2 Temperature"
      internal: true
    update_interval: 60s


