esphome:
  name: doorcam
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
        #  level: DEBUG

ota:

api:

web_server:
  port: 80

esp32_camera:
  name: Door Cam
  resolution: 640x480
  #  resolution: 320x240
  jpeg_quality: 10
  max_framerate: 10Hz
  
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

switch:
  - platform: restart
    name: "Door Cam Restart"

sensor:
  - platform: wifi_signal
    name: "Door Cam WiFi Signal Sensor"
    update_interval: 60s



