
substitutions:
  deviceName: drawer
  upperDeviceName: Stepper Motor drawer


esphome:
  name: ${deviceName}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #    ssid: "blablabla"
  #    password: !secret wifi_password

  #captive_portal:

# Enable logging
logger:

# Enable Home Assistant API

api:
  services:
    - service: control_stepper
      variables:
        target: int
      then:
        - stepper.set_target:
            id: my_stepper
            target: !lambda 'return target;'

ota:

# Example configuration entry
stepper:
  - platform: a4988
    id: my_stepper
    sleep_pin: D2
    step_pin: D3
    dir_pin: D4
    max_speed: 500 steps/s

    # Optional:


    acceleration: inf
    deceleration: 200
