
substitutions:
  devicename: dynamic_lcd
  upper_devicename: Dynamic LCD


esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

captive_portal:

mqtt:
  broker: box.local

logger:

ota:

web_server:
  port: 80    


i2c:
  sda: 26 
  scl: 25
  scan: True

font:
  - file: 'fonts/Roboto-Regular.ttf'
    id: font1
    size: 16

sensor:
  - platform: wifi_signal
    id: wific
    name: ${devicename} WiFi Signal Sensor
    update_interval: 60s


display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(font1), "AYYY LMAO!");
      it.printf(0, 48, id(font1), "Wifi strength: %.1f", id(wific).state);



