
substitutions:
  deviceName: empty
  upperDeviceName: Empty

esphome:
  name: ${deviceName}
  platform: ESP32
  board: nodemcu-32s


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

