esphome:
  name: esp32
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

#mqtt:
#  broker: box.local

logger:
  level: DEBUG

ota:

switch:
  - platform: gpio
    name: "Living Room Dehumidifier"
    pin: 5

web_server:
  port: 80    

sensor:
  - platform: wifi_signal
    name: "Testik WiFi Signal Sensor"
    update_interval: 60s

