
substitutions:
  deviceName: flowers
  upperDeviceName: Flowers
  updateInterval: 600s

esphome:
  name: ${deviceName}
  platform: ESP32
  board: esp32dev

packages:
  captive_portal: !include common/captive_portal.yaml
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  logger: !include common/logger.yaml
  #api: !include common/api.yaml
  ota: !include common/ota.yaml
  web_server: !include common/web_server.yaml

sensor:
  - <<: !include common/sensor/uptime.config.yaml
  - <<: !include common/sensor/wifi_signal.config.yaml

  - platform: adc
    id: f1
    pin: GPIO36
    attenuation: 11db
    name: "Flower 1 moisture"
    updateInterval: $updateInterval
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    filters:
      - lambda: |-
          if (x > 3.5) {
            return 0;
          } else if (x < 1.2) {
            return 100;
          } else {
            return (3.5-x) / (3.5-1.2) * 100.0;
          }


  - platform: adc
    id: f2
    pin: GPIO34
    attenuation: 11db
    name: "Flower 2 moisture"
    updateInterval: $updateInterval
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    filters:
      - lambda: |-
          if (x > 3.5) {
            return 0;
          } else if (x < 1.2) {
            return 100;
          } else {
            return (3.5-x) / (3.5-1.2) * 100.0;
          }


  - platform: adc
    id: f3
    pin: GPIO32
    attenuation: 11db
    name: "Flower 3 moisture"
    updateInterval: $updateInterval
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    filters:
      - lambda: |-
          if (x > 3.5) {
            return 0;
          } else if (x < 1.2) {
            return 100;
          } else {
            return (3.5-x) / (3.5-1.2) * 100.0;
          }

  - platform: adc
    id: f4
    pin: GPIO33
    attenuation: 11db
    name: "Flower 4 moisture"
    updateInterval: $updateInterval
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    filters:
      - lambda: |-
          if (x > 3.5) {
            return 0;
          } else if (x < 1.2) {
            return 100;
          } else {
            return (3.5-x) / (3.5-1.2) * 100.0;
          }

i2c:
  sda: 19
  scl: 18
  scan: True

font:
  - file: 'fonts/Roboto-Regular.ttf'
    id: font1
    size: 16

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(font1), "Flower 1: %.1f", id(f1).state);
      it.printf(0, 16, id(font1), "Flower 2: %.1f", id(f2).state);
      it.printf(0, 32, id(font1), "Flower 3: %.1f", id(f3).state);
      it.printf(0, 48, id(font1), "Flower 4: %.1f", id(f4).state);
