esphome:
  name: hall_lights
  platform: ESP8266
  board: esp01_1m
  includes:
    - ADE7953.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #  fast_connect: true

api:

logger:

ota:

web_server:
  port: 80    

i2c:
    sda: GPIO12
    scl: GPIO14

    #binary_sensor:
    #  - platform: gpio
    #    pin:
    #      number: GPIO13
    #      inverted: true
    #    name: "Hall lights switch 1"
    #    on_press:
    #      then:
    #        - switch.toggle: relay1

    #  - platform: gpio
    #    pin:
    #      number: GPIO5
    #      inverted: true
    #    name: "Hall lights switch 2"
    #    on_press:
    #      then:
    #        - switch.toggle: relay2

switch:
  - platform: gpio
    pin: GPIO4
    name: "Relay #1"
    id: relay1
    interlock: [relay2]

  - platform: gpio
    pin: GPIO15
    name: "Relay #2"
    id: relay2
    interlock: [relay1]


status_led:
  pin:
    number: GPIO0
    inverted: yes

sensor:
  - platform: custom
    lambda: |-
      auto ADE7953 = new ADE7953Component();
      App.register_component(ADE7953);
      return {
              ADE7953->voltage_,
              ADE7953->current1_,
              ADE7953->current2_,
              ADE7953->power1_,
              ADE7953->power2_
             };
    sensors:
      - name: "ADE7953 Voltage"
        unit_of_measurement: V
        accuracy_decimals: 1      
      - name: "ADE7953 Current 1"
        unit_of_measurement: A
        accuracy_decimals: 3      
      - name: "ADE7953 Current 2"
        unit_of_measurement: A
        accuracy_decimals: 3      
      - name: "ADE7953 Power 1"
        unit_of_measurement: W
        accuracy_decimals: 2      
      - name: "ADE7953 Power 2"
        unit_of_measurement: W
        accuracy_decimals: 2    


