
substitutions:
  devicename: mailbox_transmitter
  upper_devicename: Mailbox Transmitter

esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


web_server:

mqtt:
  broker: !secret broker_ip
  discovery: true
  keepalive: 600s
    #  on_message:
    #    - topic: ${devicename}/ota_mode
    #      payload: 'ON'
    #      then:
    #        - deep_sleep.prevent: deep_sleep_1

logger:
  level: VERBOSE

ota:

  #deep_sleep:
  #  id: deep_sleep_1
  #  run_duration: 10s
  #  sleep_duration: 0min

# Example configuration entry
remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%

# Individual switches
switch:
  - platform: template
    name: "Mailbox full"
    turn_on_action:
      remote_transmitter.transmit_jvc:
        data: 0x1234




