
substitutions:
  deviceName: mailbox-transmitter
  upperDeviceName: Mailbox Transmitter

####
####
#### Arduino IDE is used
#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE
#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE
#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE
#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE#### DO NOT USE
####
####
####

esphome:
  name: ${deviceName}
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret broker_ip
  discovery: true
  keepalive: 600s
  on_message:
    - topic: ${deviceName}/trigger
      payload: 'ON'
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            code: !secret rf_code
            protocol: 6
            repeat:
              times: 20
              wait_time: 10250us        



logger:
  level: VERY_VERBOSE

  #deep_sleep:
  #  id: deep_sleep_1
  #  run_duration: 10s
  #  sleep_duration: 0min

# Example configuration entry
remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 100%

# Individual switches
switch:
  - platform: template
    name: "Mailbox full"
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: !secret rf_code
          repeat: 
            times: 20
            wait_time: 10250us
          
          

