
substitutions:
  devicename: mailbox_receiver
  upper_devicename: Mailbox Receiver

esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#web_server:

#captive_portal:

mqtt:
  broker: !secret broker_ip
  discovery: true
  keepalive: 600s
    #  on_message:
    #    - topic: ${devicename}/ota_mode
    #      payload: 'ON'
    #      then:
    #        - deep_sleep.prevent: deep_sleep_1

logger:
  level: VERBOSE

ota:

remote_receiver:
  pin:
    number: GPIO22
      #    inverted: true
  dump: all
    #    - rc_switch
      #  tolerance: 90%
    #  filter: 2us
    #  idle: 4ms
  buffer_size: 10kb

    #  dump: all
    #  tolerance: 50%
    #  filter: 250us
    #  idle: 4ms
    #  buffer_size: 9kb

binary_sensor:
  - platform: remote_receiver
    name: RF Bridge
    rc_switch_raw:
      protocol: 1
      code: !secret rf_code
        #    filters:
        #      - delayed_off: 100ms





