
substitutions:
  devicename: stepper_motor
  upper_devicename: Stepper Motor Test


esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  #captive_portal:

# Enable logging
logger:

# Enable Home Assistant API

api:
  services:
    - service: control_stepper
      variables:
        target: int
      then:
        - stepper.set_target:
            id: ${devicename}
            target: !lambda 'return target;'

ota:

# Example configuration entry
stepper:
  - platform: a4988
    id: ${devicename}
    step_pin: GPIO4
    dir_pin: GPIO2
    max_speed: 5 steps/s

    # Optional:
    acceleration: inf
    deceleration: 200
