esphome:
  name: testik
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: IoT24
  password: !secret wifi_password
  fast_connect: true

mqtt:
  broker: box.local

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
#api:

ota:

switch:
  - platform: gpio
    name: "Living Room Dehumidifier"
    pin: 5


web_server:
  port: 80    

sensor:
  - platform: wifi_signal
    name: "Testik WiFi Signal Sensor"
    updateInterval: 60s

  - platform: adc
    pin: VCC
    name: "Testik VCC Voltage"
