
substitutions:
  devicename: vindriktning
  upper_devicename: Particle Sensor
  update_interval: 600s

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  logger: !include common/logger.yaml
  #api: !include common/api.yaml
  ota: !include common/ota.yaml
  web_server: !include common/web_server.yaml

captive_portal:

sensor:
  - <<: !include common/sensor/uptime.config.yaml
  - <<: !include common/sensor/wifi_signal.config.yaml
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"

uart:
  rx_pin: D2
  baud_rate: 9600
