
substitutions:
  deviceName: xiaomi-flora
  upperDeviceName: Xiaomi Flora
  updateInterval: 600s

esphome:
  name: $deviceName
  platform: ESP32
  board: nodemcu-32s

packages:
  captive_portal: !include common/captive_portal.yaml
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  logger: !include common/logger.yaml
  #api: !include common/api.yaml
  ota: !include common/ota.yaml
  web_server: !include common/web_server.yaml

sensor:
  - <<: !include common/sensor/uptime.config.yaml
  - <<: !include common/sensor/wifi_signal.config.yaml

  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:B0:20:98'
    temperature:
      name: "MiFlora 7 Temperature"
    moisture:
      name: "MiFlora 7 Moisture"
    illuminance:
      name: "MiFlora 7 Illuminance"
    conductivity:
      name: "MiFlora 7 Soil Conductivity"

  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:B0:1F:D1'
    temperature:
      name: "MiFlora 8 Temperature"
    moisture:
      name: "MiFlora 8 Moisture"
    illuminance:
      name: "MiFlora 8 Illuminance"
    conductivity:
      name: "MiFlora 8 Soil Conductivity"

  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:B0:20:4A'
    temperature:
      name: "MiFlora 9 Temperature"
    moisture:
      name: "MiFlora 9 Moisture"
    illuminance:
      name: "MiFlora 9 Illuminance"
    conductivity:
      name: "MiFlora 9 Soil Conductivity"

  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:B0:20:47'
    temperature:
      name: "MiFlora 10 Temperature"
    moisture:
      name: "MiFlora 10 Moisture"
    illuminance:
      name: "MiFlora 10 Illuminance"
    conductivity:
      name: "MiFlora 10 Soil Conductivity"

  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:B0:20:4F'
    temperature:
      name: "MiFlora 11 Temperature"
    moisture:
      name: "MiFlora 11 Moisture"
    illuminance:
      name: "MiFlora 11 Illuminance"
    conductivity:
      name: "MiFlora 11 Soil Conductivity"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

